import Table from "./Table";
import Row from "./TableRow";
import Cell from "./TableCell";
import HeaderRow from './HeaderRow';
import HeaderCell from './HeaderCell';
import CellRender from "./CellRender";
Table.Row = Row;
Table.Cell = Cell;
Table.CellRender = CellRender;
Table.HeaderRow = HeaderRow;
Table.HeaderCell = HeaderCell;
export default Table;